AppBundle\Entity\User:
    type: entity
    table: null
#    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: string
            length: 255
            id: true
            generator:
                strategy: NONE
    fields:
        username:
            type: string
            length: 255
            unique: true
        email:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
